In [2]:
import numpy as np

a = np.array([5,67,13,100])
b=np.array([2,4,5,10])

div = a/b

div

array([ 2.5 , 16.75,  2.6 , 10.  ])

In [3]:
div2 = np.divide(a,b)

div2

array([ 2.5 , 16.75,  2.6 , 10.  ])

In [4]:
add = a+b 

add

array([  7,  71,  18, 110])

In [5]:
add_2 = np.add(a,b)

add_2

array([  7,  71,  18, 110])

In [6]:
sub = np.subtract(a,b)

sub

array([ 3, 63,  8, 90])

In [7]:
mul = np.multiply(a,b)
mul

array([  10,  268,   65, 1000])

In [11]:
# indexing 

a = np.arange(12,1,-1)

a

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [12]:
# indexes are specified inside the np.array method 

newarr = a[np.array([3,1,2])]

newarr

array([ 9, 11, 10])

In [13]:
a = np.arange(20)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
a[-15:12:1]

array([ 5,  6,  7,  8,  9, 10, 11])

In [17]:
a[14:]

array([14, 15, 16, 17, 18, 19])

In [19]:
arr = np.linspace(0,10,20)

arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
arr = np.arange(0,10,2)

arr

array([0, 2, 4, 6, 8])

In [22]:
arr = np.linspace(0,100,5)

arr

array([  0.,  25.,  50.,  75., 100.])

In [23]:
# random numbers

arr = np.random.rand(10)
arr

array([0.66340633, 0.55444378, 0.33032966, 0.59927328, 0.05544858,
       0.12277112, 0.97501184, 0.93428275, 0.84978975, 0.92428687])

In [24]:
arr

array([0.66340633, 0.55444378, 0.33032966, 0.59927328, 0.05544858,
       0.12277112, 0.97501184, 0.93428275, 0.84978975, 0.92428687])

In [25]:
arr1 = np.random.rand(3,4)

arr1

array([[0.42249562, 0.12150301, 0.49910585, 0.78512013],
       [0.71902889, 0.80033512, 0.42465989, 0.22191415],
       [0.89550837, 0.26320674, 0.44081759, 0.82369326]])

In [26]:
arr

array([0.66340633, 0.55444378, 0.33032966, 0.59927328, 0.05544858,
       0.12277112, 0.97501184, 0.93428275, 0.84978975, 0.92428687])

In [27]:
arr1

array([[0.42249562, 0.12150301, 0.49910585, 0.78512013],
       [0.71902889, 0.80033512, 0.42465989, 0.22191415],
       [0.89550837, 0.26320674, 0.44081759, 0.82369326]])

In [28]:
arr,arr1

(array([0.66340633, 0.55444378, 0.33032966, 0.59927328, 0.05544858,
        0.12277112, 0.97501184, 0.93428275, 0.84978975, 0.92428687]),
 array([[0.42249562, 0.12150301, 0.49910585, 0.78512013],
        [0.71902889, 0.80033512, 0.42465989, 0.22191415],
        [0.89550837, 0.26320674, 0.44081759, 0.82369326]]))

In [29]:
# array of constant values in a given shape 

np.full((4,6),10) # 4 rows and 6 columns of value 10 

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [30]:
# create an array by repetition
# repeat each element of an array by a specified numbers of times 

arr = [0,1,2]

np.repeat(arr,2)

array([0, 0, 1, 1, 2, 2])

In [31]:
# repeat the array by specified number of times 

arr = [5,6,7,9]

np.tile(arr,4)



array([5, 6, 7, 9, 5, 6, 7, 9, 5, 6, 7, 9, 5, 6, 7, 9])

In [32]:
# identity matrix 

identity_matrix = np.eye(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
identity_matrix = np.identity(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# random array

arr = np.random.rand(4,4)

arr

array([[0.91797405, 0.19364589, 0.64404432, 0.35442734],
       [0.64868505, 0.06157183, 0.67037144, 0.83877505],
       [0.79926186, 0.76682312, 0.18062407, 0.55248018],
       [0.67968085, 0.1933886 , 0.36022581, 0.61540519]])

In [36]:
arr

array([[0.91797405, 0.19364589, 0.64404432, 0.35442734],
       [0.64868505, 0.06157183, 0.67037144, 0.83877505],
       [0.79926186, 0.76682312, 0.18062407, 0.55248018],
       [0.67968085, 0.1933886 , 0.36022581, 0.61540519]])

In [37]:
arr1 = np.random.rand(3,4)

arr1

array([[0.36509728, 0.94671545, 0.05429361, 0.29583741],
       [0.56544857, 0.11441507, 0.8031029 , 0.03833475],
       [0.88306015, 0.75636711, 0.52877002, 0.23972444]])

In [38]:
arr_sum = np.sum(arr,axis=0) # sum along with columns 

arr_sum

array([3.04560181, 1.21542943, 1.85526564, 2.36108776])

In [39]:
np.sum([0.67968085, 0.1933886 , 0.36022581, 0.61540519]) 

1.84870045

In [40]:
np.sum([0.91797405,0.64868505,0.79926186,0.67968085])

3.04560181

In [42]:
np.sum(arr,axis=1)  # sum along with rows

array([2.1100916 , 2.21940336, 2.29918922, 1.84870046])

In [43]:
# mean, median, std, var 

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5298365400910616
0.6297247576103358
0.25969111597786293
0.06743947571782785


In [44]:
# sort an array 

arr = np.random.rand(3,3)
arr

array([[0.06758383, 0.22999296, 0.21803539],
       [0.43999761, 0.54245403, 0.57554573],
       [0.67204667, 0.60292697, 0.95899745]])

In [46]:
arr_sort = np.sort(arr,axis=1)

arr_sort

array([[0.06758383, 0.21803539, 0.22999296],
       [0.43999761, 0.54245403, 0.57554573],
       [0.60292697, 0.67204667, 0.95899745]])

In [47]:

arr = np.array([45,67,200])
arr

array([ 45,  67, 200])

In [48]:
arr1 = np.append(arr,100) # append () method 
arr1

array([ 45,  67, 200, 100])

In [50]:
arr2= np.append(arr1,[1000,202,503])

arr2

array([  45,   67,  200,  100, 1000,  202,  503])

In [52]:
# delete multiple elements 

arr3 = np.delete(arr2, [1,4])  # delete 1 and 4 index elements 

arr3

array([ 45, 200, 100, 202, 503])

In [54]:
arr4 = np.delete(arr3,[2,3])
arr4



array([ 45, 200, 503])

In [56]:
# concatenate elements 

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])

cat_arr = np.concatenate((arr1,arr2),axis=0)

cat_arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])