In [2]:
import numpy as np

data = np.loadtxt("data.txt") # read file using numpy
data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [3]:
data = np.loadtxt('data_with_header.txt',skiprows=1,delimiter=",") # skip the header and delimiter by ","

data

array([[12., 45., 55.],
       [11., 41.,  5.],
       [10., 20., 40.]])

In [6]:
data = np.loadtxt('data.txt',usecols=(0,2))

data

array([[1., 3.],
       [4., 6.],
       [7., 9.]])

In [7]:
# read the binary file format

data =np.fromfile('data.bin',dtype=np.float32)

data

array([1.5087838e-19, 1.5249968e-19, 8.7690387e-33, 1.5596065e-19],
      dtype=float32)

In [8]:
data = np.genfromtxt('data_with_header.csv',delimiter=",",names=True) # read a csv file with headers

data

array([( 12.,  56.,  55.), (109., 100.,  56.), ( 55.,  99., 101.)],
      dtype=[('Num1', '<f8'), ('Num2', '<f8'), ('Num3', '<f8')])

In [10]:
# saving a Numpy array to a text file 

data = np.array([[12,56,100],[56,66,101],[51,50,12]])

np.savetxt('data_output.txt',data)

print("Data file saved successfully")


Data file saved successfully


In [11]:
# save numpy array into binary file 

np.save('data_output.npy',data)

print("File saved successfully")

File saved successfully


In [12]:
# loading a numpy array from a binary file 

data =np.load('data_output.npy')

data

array([[ 12,  56, 100],
       [ 56,  66, 101],
       [ 51,  50,  12]])